INDEX_NAME = 'covid19'

BASE_EPIDEMIOLOGICAL_URL = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data' \
                           '/csse_covid_19_daily_reports/{:02d}-{:02d}-{}.csv'
BASE_RESTRICTIONS_URL = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv'
BASE_POPULATION_URL = 'https://raw.githubusercontent.com/datasets/population/master/data/population.csv'

EPIDEMIOLOGICAL_COLUMNS_TYPES = {
    'Active': 'float64',
    'Deaths': 'float64',
    'Confirmed': 'float64',
    'Recovered': 'float64',
    'Country_Region': 'string',
    'Lat': 'float32',
    'Long_': 'float32'
}
RESTRICTIONS_COLUMNS_TYPES = {
    'C1_School closing': 'float32',
    'C2_Workplace closing': 'float32',
    'C3_Cancel public events': 'float32',
    'C4_Restrictions on gatherings': 'float32',
    'C5_Close public transport': 'float32',
    'C6_Stay at home requirements': 'float32',
    'C7_Restrictions on internal movement': 'float32',
    'C8_International travel controls': 'float32',
    'E4_International support': 'float32',
    'H1_Public information campaigns': 'float32',
    'H2_Testing policy': 'float32',
    'H3_Contact tracing': 'float32',
    'H5_Investment in vaccines': 'float32',
    'H6_Facial Coverings': 'float32',
    'H7_Vaccination policy': 'float32',
    'StringencyIndex': 'float32',
    'GovernmentResponseIndex': 'float32',
    'ContainmentHealthIndex': 'float32',
    'EconomicSupportIndex': 'float32',
    'CountryCode': 'string',
    'Date': 'int64'
}
POPULATION_COLUMNS_TYPES = {
    'Country Code': 'string',
    'Value': 'int64'
}

EPIDEMIOLOGICAL_AGGREGATIONS = {
    'Active': 'sum',
    'Deaths': 'sum',
    'Confirmed': 'sum',
    'Recovered': 'sum',
    'CountryCode': 'last',
    'Lat': 'mean',
    'Long_': 'mean',
    'timestamp': 'last'
}
RESTRICTIONS_AGGREGATIONS = {
    'C1_School closing': 'mean',
    'C2_Workplace closing': 'mean',
    'C3_Cancel public events': 'mean',
    'C4_Restrictions on gatherings': 'mean',
    'C5_Close public transport': 'mean',
    'C6_Stay at home requirements': 'mean',
    'C7_Restrictions on internal movement': 'mean',
    'C8_International travel controls': 'mean',
    'E4_International support': 'mean',
    'H1_Public information campaigns': 'mean',
    'H2_Testing policy': 'mean',
    'H3_Contact tracing': 'mean',
    'H5_Investment in vaccines': 'mean',
    'H6_Facial Coverings': 'mean',
    'H7_Vaccination policy': 'mean',
    'StringencyIndex': 'mean',
    'GovernmentResponseIndex': 'mean',
    'ContainmentHealthIndex': 'mean',
    'EconomicSupportIndex': 'mean',
    'CountryCode': 'last',
    'timestamp': 'last'
}
POPULATION_AGGREGATIONS = {
    'Population': 'last'
}

COUNTRY_CODES_MAP = {
    "Afghanistan": "AFG",
    "Albania": "ALB",
    "Algeria": "DZA",
    "Andorra": "AND",
    "Angola": "AGO",
    "Argentina": "ARG",
    # "Armenia": "ARM",
    "Australia": "AUS",
    "Austria": "AUT",
    "Azerbaijan": "AZE",
    "Bahamas": "BHS",
    "Bahrain": "BHR",
    "Bangladesh": "BGD",
    "Barbados": "BRB",
    "Belarus": "BLR",
    "Belgium": "BEL",
    "Belize": "BLZ",
    "Benin": "BEN",
    "Bhutan": "BTN",
    "Bolivia": "BOL",
    "Bosnia and Herzegovina": "BIH",
    "Botswana": "BWA",
    "Brazil": "BRA",
    "Brunei": "BRN",
    "Bulgaria": "BGR",
    "Burkina Faso": "BFA",
    "Burma": "MMR",
    "Burundi": "BDI",
    "Cabo Verde": "CPV",
    "Cambodia": "KHM",
    "Cameroon": "CMR",
    "Canada": "CAN",
    "Central African Republic": "CAF",
    "Chad": "TCD",
    "Chile": "CHL",
    "China": "CHN",
    "Colombia": "COL",
    "Comoros": "COM",
    "Congo (Brazzaville)": "COD",
    "Congo (Kinshasa)": "COD",
    "Costa Rica": "CRI",
    "Cote d'Ivoire": "CIV",
    "Croatia": "HRV",
    "Cuba": "CUB",
    "Cyprus": "CYP",
    "Czechia": "CZE",
    "Denmark": "DNK",
    "Djibouti": "DJI",
    "Dominica": "DMA",
    "Dominican Republic": "DOM",
    "Ecuador": "ECU",
    "Egypt": "EGY",
    "El Salvador": "SLV",
    # "Equatorial Guinea": "GNQ",
    "Eritrea": "ERI",
    "Estonia": "EST",
    "Eswatini": "SWZ",
    "Ethiopia": "ETH",
    "Fiji": "FJI",
    "Finland": "FIN",
    "France": "FRA",
    "Gabon": "GAB",
    "Gambia": "GMB",
    "Georgia": "GEO",
    "Germany": "DEU",
    "Ghana": "GHA",
    "Greece": "GRC",
    # "Grenada": "GRD",
    "Guatemala": "GTM",
    "Guinea": "GIN",
    # "Guinea-Bissau": "GNB",
    "Guyana": "GUY",
    "Haiti": "HTI",
    # "Holy See": "VAT",
    "Honduras": "HND",
    "Hungary": "HUN",
    "Iceland": "ISL",
    "India": "IND",
    "Indonesia": "IDN",
    "Iran": "IRN",
    "Iraq": "IRQ",
    "Ireland": "IRL",
    "Israel": "ISR",
    "Italy": "ITA",
    "Jamaica": "JAM",
    "Japan": "JPN",
    "Jordan": "JOR",
    "Kazakhstan": "KAZ",
    "Kenya": "KEN",
    "Korea, South": "KOR",
    "Kosovo": "SRB",
    "Kuwait": "KWT",
    "Kyrgyzstan": "KGZ",
    "Laos": "LAO",
    "Latvia": "LVA",
    "Lebanon": "LBN",
    "Lesotho": "LSO",
    "Liberia": "LBR",
    "Libya": "LBY",
    "Liechtenstein": "LIE",
    "Lithuania": "LTU",
    "Luxembourg": "LUX",
    "Madagascar": "MDG",
    "Malawi": "MWI",
    "Malaysia": "MYS",
    # "Maldives": "MDV",
    "Mali": "MLI",
    "Malta": "MLT",
    # "Marshall Islands": "MHL",
    "Mauritania": "MRT",
    "Mauritius": "MUS",
    "Mexico": "MEX",
    "Moldova": "MDA",
    "Monaco": "MCO",
    "Mongolia": "MNG",
    # "Montenegro": "MNE",
    "Morocco": "MAR",
    "Mozambique": "MOZ",
    "Namibia": "NAM",
    "Nepal": "NPL",
    "Netherlands": "NLD",
    "New Zealand": "NZL",
    "Nicaragua": "NIC",
    "Niger": "NGA",
    "Nigeria": "NGA",
    # "North Macedonia": "MKD",
    "Norway": "NOR",
    "Oman": "OMN",
    "Pakistan": "PAK",
    "Panama": "PAN",
    "Papua New Guinea": "PNG",
    "Paraguay": "PRY",
    "Peru": "PER",
    "Philippines": "PHL",
    "Poland": "POL",
    "Portugal": "PRT",
    "Qatar": "QAT",
    "Romania": "ROU",
    "Russia": "RUS",
    "Rwanda": "RWA",
    # "Saint Kitts and Nevis": "KNA",
    # "Saint Lucia": "LCA",
    # "Saint Vincent and the Grenadines": "VCT",
    # "Samoa": "WSM",
    "San Marino": "SMR",
    # "Sao Tome and Principe": "STP",
    "Saudi Arabia": "SAU",
    "Senegal": "SEN",
    "Serbia": "SRB",
    "Seychelles": "SYC",
    "Sierra Leone": "SLE",
    "Singapore": "SGP",
    "Slovakia": "SVK",
    "Slovenia": "SVN",
    "Solomon Islands": "SLB",
    "Somalia": "SOM",
    "South Africa": "ZAF",
    "South Sudan": "SSD",
    "Spain": "ESP",
    "Sri Lanka": "LKA",
    "Sudan": "SDN",
    "Suriname": "SUR",
    "Sweden": "SWE",
    "Switzerland": "CHE",
    "Syria": "SYR",
    "Taiwan*": "TWN",
    "Tajikistan": "TJK",
    "Tanzania": "TZA",
    "Thailand": "THA",
    "Timor-Leste": "TLS",
    "Togo": "TGO",
    "Trinidad and Tobago": "TTO",
    "Tunisia": "TUN",
    "Turkey": "TUR",
    "US": "USA",
    "Uganda": "UGA",
    "Ukraine": "UKR",
    "United Arab Emirates": "ARE",
    "United Kingdom": "GBR",
    "Uruguay": "URY",
    "Uzbekistan": "UZB",
    "Vanuatu": "VUT",
    "Venezuela": "VEN",
    "Vietnam": "VNM",
    "Yemen": "YEM",
    "Zambia": "ZMB",
    "Zimbabwe": "ZWE"
}
COUNTRY_CODES = set(COUNTRY_CODES_MAP.values())
